### ISSUE TITLE
Market data not printed

### ISSUE THREAD

**Issue by ljcljc** [femtotrader/ig-markets-stream-api-python-library#6]
Hi, I tried the sample with my account, and the log has such error:

TransientError: ERROR -1: Invalid account type

I used my LIVE account, which works fine with REST api and minute data, but I want to have tick data with stream api. The account information is exactly the same.

So, could anyone give me some hint?

Thanks

**Comment by femtotrader** [comment]
Hi,

Which version of Python ?

Kind regards

**Comment by femtotrader** [comment]
pc:ig-markets-stream-api-python-library femto$ source activate py2
    discarding //anaconda/bin from PATH
    prepending //anaconda/envs/py2/bin to PATH

    (py2)pc:ig-markets-stream-api-python-library femto$ python sample.py
    ('New state:', 'connecting Lightstreamer session')
    ('New state:', 'connected Lightstreamer session')
    balance update = [u'29969.47']
    price update = [u'09:47:04', u'1.55388', u'1.55408', u'0.00099', u'TRADEABLE']
    price update = [u'09:47:09', u'1.55393', u'1.55403', u'0.00099', u'TRADEABLE']
    price update = [u'09:47:10', u'1.55394', u'1.55404', u'0.00100', u'TRADEABLE']
    price update = [u'09:47:10', u'1.55401', u'1.55411', u'0.00107', u'TRADEABLE']
    price update = [u'09:47:10', u'1.55402', u'1.55412', u'0.00108', u'TRADEABLE']
    price update = [u'09:47:11', u'1.55400', u'1.55410', u'0.00106', u'TRADEABLE']
    price update = [u'09:47:11', u'1.55399', u'1.55409', u'0.00105', u'TRADEABLE']
    price update = [u'09:47:11', u'1.55397', u'1.55407', u'0.00103', u'TRADEABLE']
    price update = [u'09:47:14', u'1.55391', u'1.55411', u'0.00102', u'TRADEABLE']
    price update = [u'09:47:14', u'1.55389', u'1.55409', u'0.00100', u'TRADEABLE']
    price update = [u'09:47:14', u'1.55388', u'1.55408', u'0.00099', u'TRADEABLE']
    price update = [u'09:47:21', u'1.55394', u'1.55404', u'0.00100', u'TRADEABLE']


    (py2)pc:ig-markets-stream-api-python-library femto$ python --version
    Python 2.7.10 :: Anaconda 2.3.0 (x86_64)

**Comment by ljcljc** [comment]
Hi, thanks for your replay.
I use python 2.7.10, same with you. But this is all I have here. I have created a new DEMO account, but it's still not working

('New state:', 'connecting Lightstreamer session')
('New state:', 'connected Lightstreamer session')
balance update = [u'10000.00']


No price data is printed. Here is the log error:
2015-09-21 17:05:14,620 ERROR While invoking <bound method LsClient._send_control_impl of <igls.LsClient object at 0x10b6f2750>>(*(), **{})
Traceback (most recent call last):
  File "/Users/jiechaoli/Lzzg/ig_api/ig-markets-stream-api-python-library/igls.py", line 199, in run_and_log
    func(*args, **kwargs)
  File "/Users/jiechaoli/Lzzg/ig_api/ig-markets-stream-api-python-library/igls.py", line 647, in _send_control_impl
    self._parse_and_raise_status(req, req.iter_lines())
  File "/Users/jiechaoli/Lzzg/ig_api/ig-markets-stream-api-python-library/igls.py", line 542, in _parse_and_raise_status
    (status, next(line_it), next(line_it)))
TransientError: ERROR -1: Invalid account type

**Comment by ljcljc** [comment]
I have another idea, could you use my account info and see if it works?

I want to know whether it's a problem of my account. Here it is.
    username = "chrisdemo"
    password = "Lzqh12345!"
    api_key = '48ba772792217e8d048d9666e41eb9a488ed8444'
    acc_type = "DEMO" # LIVE / DEMO
    acc_number = "luzhengam_test"

Thanks

**Comment by femtotrader** [comment]
With your demo credentials I'm getting only

    $ python sample.py
    ('New state:', 'connecting Lightstreamer session')
    ('New state:', 'connected Lightstreamer session')
    balance update = [u'10000.00']

no `price update`
switching to my credential I get `price_update`

my account number looks like `AA1AA` where A stands for a letter, 1 stands for a number

**Comment by ljcljc** [comment]
OK, then it's definitely my account's problem. I have tested with both my LIVE and DEMO account, and none of them work.

**Comment by ljcljc** [comment]
I found my account number
![image](https://cloud.githubusercontent.com/assets/1289836/9988992/aecfb12e-6087-11e5-99a8-a2546e8b3579.png)
So, it changed it to 'XL66S' and 'XL66T', but still not working

**Comment by ljcljc** [comment]
hi, femtotrader
Could you tell me the type of your account? Mine is a regular LIVE account, not pro. Does it need to be PRO to get tick data?

**Comment by femtotrader** [comment]
Sorry I can't say for now... because my demo account seems to be disabled (I can't login to web interface). But I can oddly connect to API and see price update ;-)

**Comment by ljcljc** [comment]
I have applied for a new account and the demo works now. Thanks a lot!

**Comment by femtotrader** [comment]
Thanks.

Feel free to also help development on Python 3 support

[Weswit/Lightstreamer-example-StockList-client-python](https://github.com/Weswit/Lightstreamer-example-StockList-client-python) now have Python 3 support so it should help

**Comment by ljcljc** [comment]
Thanks. I will take a look at it as soon as I finish my current project.

On Sun, Sep 27, 2015 at 2:37 PM, femtotrader <notifications@github.com>
wrote:

> Thanks.
>
> Feel free to also help development on Python 3 support
>
> Weswit/Lightstreamer-example-StockList-client-python
> <https://github.com/Weswit/Lightstreamer-example-StockList-client-python>
> now have Python 3 support so it should help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/femtotrader/ig-markets-stream-api-python-library/issues/6#issuecomment-143523947>
> .
>



-- 
Best wishes

Jiechao Li

**Comment by femtotrader** [comment]
I suggest using Anaconda Python.
You can switch easily Python version (from 2 to 3 or 3 to 2)
http://continuum.io/blog/anaconda-python-3

**Comment by ljcljc** [comment]
hi, do you know how to subscribe to multiple items? For example, I want to get realtime price of 'GBPUSD' and 'EURUSD' and others..

**Comment by ljcljc** [comment]
I got it. Just use item_ids='L1:CS.D.GBPUSD.CFD.IP L1:CS.D.EURUSD.CFD.IP'

But, when the price comes, I do not know which price is from which item. I can only get item is an integer. Is it the index of item in the string list?

**Comment by femtotrader** [comment]
try with ";" or ","

**Comment by femtotrader** [comment]
Sorry I misunderstood your question. I need to have a look deeper

**Comment by ljcljc** [comment]
Well. I assume the order I put in item_id correspond to item. For example, item_ids='L1:CS.D.GBPUSD.CFD.IP L1:CS.D.EURUSD.CFD.IP'

Then, 
'item 1' means  GBPUSD
'item 2' means EURUSD

**Comment by femtotrader** [comment]
If I where you I will add some other symbol (with JPY for example) to be sure of this

**Comment by ljcljc** [comment]
Thanks, do you know where is the complete list of all the market I can access? and their valid epic name?

**Comment by femtotrader** [comment]
Someone scrapped a web page

http://www.andlil.com/forum/epics-source-t9986.html#p308583

http://www.andlil.com/api/Epics/log_epics.txt

http://www.andlil.com/api/Epics/

**Comment by ljcljc** [comment]
Great! Thanks
